### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by MrBlasyMSK** [Hydros01/WorldBorder#3]
```yml
# The border builds out from the default spawn coords.
# Say my world spawn is "30, 62, 30"; the border will have a 30 block offset.

border:
  #World name: size
  Facciones: 50000
prefix: "[!]"
#-------------------------#
```
![image](https://user-images.githubusercontent.com/85447029/160728059-33d64a7a-da59-4aae-895a-2c879ea2bd1a.png)
Im using the dev13
OS: linux
PHP: 8.0.17
Pocketmine: 4.2.5
