### ISSUE TITLE
The maximum limit is exceeded by more than 350 blocks.

### ISSUE THREAD

**Issue by MrBlasyMSK** [Hydros01/WorldBorder#4]
```yml
border:
  #World name: size
  Facciones: 50000
prefix: "[!]"
```
Chech the video https://streamable.com/biw4ms

Dev: 17
PHP: 8.0.17
OS: linux
Pocketmine: 4.2.5
